version: "3.10"

services:
  db:
    image: postgres:12
    container_name: postgres_db_beta
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    env_file:
      - ./.env
    ports:
      - 5434:5432
    networks:
      - my_network
  web:
    build: .
    container_name: django_local_server
    command: bash -c "python -m uvicorn app.delivery.web.asgi:application --host 0.0.0.0 --port 8001"
    volumes:
      - .:/code
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    networks:
      - my_network
  bot:
    build: .
    container_name: tg_bot
    command: bash -c "python -m app.delivery.bot"
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - web
    networks:
      - my_network


volumes:
  postgres_data:

networks:
  my_network: