# Generated by Django 4.2.4 on 2023-08-15 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcernHandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание решения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Решение",
                "verbose_name_plural": "Решения",
            },
        ),
        migrations.CreateModel(
            name="ConcernImportance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Критичность обеспокоенности",
                "verbose_name_plural": "Критичность обеспокоенностей",
            },
        ),
        migrations.CreateModel(
            name="ConcernName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Классификатор обеспокоенности",
                "verbose_name_plural": "Классификаторы обеспокоенностей",
            },
        ),
        migrations.CreateModel(
            name="Concerns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concern_title",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Наименование обеспокоенности",
                    ),
                ),
                (
                    "concern_description",
                    models.TextField(verbose_name="Описание обеспокоенности"),
                ),
                (
                    "concern_effect",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Экономический эффект",
                    ),
                ),
                (
                    "concern_reason",
                    models.TextField(verbose_name="Предполагаемая причина"),
                ),
                (
                    "concern_solution",
                    models.TextField(verbose_name="Предполагаемое решение"),
                ),
                (
                    "added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления в базу данных"
                    ),
                ),
            ],
            options={
                "verbose_name": "Зарегистированная обеспокоенность",
                "verbose_name_plural": "Зарегистированные обеспокоенности",
                "ordering": ["-added"],
            },
        ),
        migrations.CreateModel(
            name="ConcernStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус обеспокоенности",
                "verbose_name_plural": "Статусы обеспокоенностей",
            },
        ),
        migrations.CreateModel(
            name="ConcernUrgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Срочность обеспокоенности",
                "verbose_name_plural": "Срочность обеспокоенностей",
            },
        ),
        migrations.CreateModel(
            name="CustomNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("info", "info"),
                            ("warning", "warning"),
                            ("error", "error"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="level",
                    ),
                ),
                (
                    "unread",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="unread"
                    ),
                ),
                (
                    "actor_object_id",
                    models.CharField(max_length=255, verbose_name="actor object id"),
                ),
                ("verb", models.CharField(max_length=255, verbose_name="verb")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="target object id",
                    ),
                ),
                (
                    "action_object_object_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="action object object id",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="public"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="deleted"
                    ),
                ),
                (
                    "emailed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="emailed"
                    ),
                ),
                (
                    "data",
                    jsonfield.fields.JSONField(
                        blank=True, null=True, verbose_name="data"
                    ),
                ),
                (
                    "action_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_action_object",
                        to="contenttypes.contenttype",
                        verbose_name="action object content type",
                    ),
                ),
                (
                    "actor_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_actor",
                        to="contenttypes.contenttype",
                        verbose_name="actor content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
