# Generated by Django 4.2.4 on 2023-08-15 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("handling_concerns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient",
            ),
        ),
        migrations.AddField(
            model_name="customnotification",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notify_target",
                to="contenttypes.contenttype",
                verbose_name="target content type",
            ),
        ),
        migrations.AddField(
            model_name="concerns",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор обеспокоенности",
            ),
        ),
        migrations.AddField(
            model_name="concerns",
            name="concern_importance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="handling_concerns.concernimportance",
                verbose_name="Критичность обеспокоенности",
            ),
        ),
        migrations.AddField(
            model_name="concerns",
            name="concern_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="handling_concerns.concernname",
                verbose_name="Классификатор обеспокоенности",
            ),
        ),
        migrations.AddField(
            model_name="concerns",
            name="concern_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="handling_concerns.concernstatus",
                verbose_name="Статус обеспокоенности",
            ),
        ),
        migrations.AddField(
            model_name="concerns",
            name="concern_urgency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="handling_concerns.concernurgency",
                verbose_name="Срочность обеспокоенности",
            ),
        ),
        migrations.AddField(
            model_name="concernname",
            name="company_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
                verbose_name="Название компании",
            ),
        ),
        migrations.AddField(
            model_name="concernhandle",
            name="concern",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="handling_concerns.concerns",
                verbose_name="Обеспокоенность",
            ),
        ),
        migrations.AddField(
            model_name="concernhandle",
            name="responsible_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный пользователь",
            ),
        ),
    ]
