# Generated by Django 4.2.4 on 2023-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TGUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Telegram User ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(blank=True, verbose_name="Telegram Chat ID"),
                ),
            ],
            options={
                "db_table": "tg_user",
            },
        ),
    ]
